/** Need to remove features from ignore list as they are added to our app. */

module.exports = {
  styleguideDir: "styleguide",
  components: "src/**/*.js",
  title: "dictyBase DictyAccess",
  ignore: [
    "**/*.test.{js,jsx,ts,tsx}",
    "**/*Actions.js",
    "**/*Constants.js",
    "**/*Reducer.js",
    "**/*Store.js",
    "**/*Styles.js",
    "src/common/assets/*.png",
    "src/common/constants/*.js",
    "src/common/data/*.js",
    "src/common/styles/*.js",
    "src/common/utils/*.js",
    "src/features/Analytics/*.js",
    "src/features/Analytics/Charts/*.js",
    "src/features/Annotations/*.js",
    "src/features/Annotations/Charts/*.js",
    "src/features/Annotations/Lists/*.js",
    "src/features/BirdsEye/Circos/utils/*.js",
    "src/features/Genomes/*.js",
    "src/features/Genomes/Charts/*.js",
    "src/features/Genomes/Tables/*.js",
    "src/features/Phylogeny/*.js",
    "src/features/StockCenter/*.js",
    "src/features/StockCenter/Charts/*.js",
    "src/features/StockCenter/Lists/*.js",
    "src/features/StockCenter/Tables/*.js",
    "src/index.js",
    "src/registerServiceWorker.js",
    "src/setupTests.js",
  ],
}
