// flow-typed signature: effae834d5491176d57d6643115b4bd6
// flow-typed version: <<STUB>>/circos_v2.x.x/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'circos'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "circos" {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "circos/demo/axes/index" {
  declare module.exports: any
}

declare module "circos/demo/chords" {
  declare module.exports: any
}

declare module "circos/demo/heatmap" {
  declare module.exports: any
}

declare module "circos/demo/highlight" {
  declare module.exports: any
}

declare module "circos/demo/histogram" {
  declare module.exports: any
}

declare module "circos/demo/line" {
  declare module.exports: any
}

declare module "circos/demo/scatter" {
  declare module.exports: any
}

declare module "circos/demo/stack" {
  declare module.exports: any
}

declare module "circos/demo/text" {
  declare module.exports: any
}

declare module "circos/dist/circos.es6" {
  declare module.exports: any
}

declare module "circos/dist/circos" {
  declare module.exports: any
}

declare module "circos/dist/circos.min" {
  declare module.exports: any
}

declare module "circos/layout-conf" {
  declare module.exports: any
}

declare module "circos/src/axes" {
  declare module.exports: any
}

declare module "circos/src/axes.test" {
  declare module.exports: any
}

declare module "circos/src/behaviors/tooltip" {
  declare module.exports: any
}

declare module "circos/src/circos" {
  declare module.exports: any
}

declare module "circos/src/clipboard" {
  declare module.exports: any
}

declare module "circos/src/colors" {
  declare module.exports: any
}

declare module "circos/src/colors.test" {
  declare module.exports: any
}

declare module "circos/src/config-utils" {
  declare module.exports: any
}

declare module "circos/src/configs" {
  declare module.exports: any
}

declare module "circos/src/data-parser" {
  declare module.exports: any
}

declare module "circos/src/data-parser.test" {
  declare module.exports: any
}

declare module "circos/src/layout/conf" {
  declare module.exports: any
}

declare module "circos/src/layout/index" {
  declare module.exports: any
}

declare module "circos/src/layout/render" {
  declare module.exports: any
}

declare module "circos/src/logger" {
  declare module.exports: any
}

declare module "circos/src/render" {
  declare module.exports: any
}

declare module "circos/src/scales" {
  declare module.exports: any
}

declare module "circos/src/tracks/Chords" {
  declare module.exports: any
}

declare module "circos/src/tracks/Heatmap" {
  declare module.exports: any
}

declare module "circos/src/tracks/Heatmap.test" {
  declare module.exports: any
}

declare module "circos/src/tracks/Highlight" {
  declare module.exports: any
}

declare module "circos/src/tracks/Histogram" {
  declare module.exports: any
}

declare module "circos/src/tracks/Line" {
  declare module.exports: any
}

declare module "circos/src/tracks/Line.test" {
  declare module.exports: any
}

declare module "circos/src/tracks/Scatter" {
  declare module.exports: any
}

declare module "circos/src/tracks/Stack" {
  declare module.exports: any
}

declare module "circos/src/tracks/Text" {
  declare module.exports: any
}

declare module "circos/src/tracks/Track" {
  declare module.exports: any
}

declare module "circos/src/utils" {
  declare module.exports: any
}

declare module "circos/src/utils.test" {
  declare module.exports: any
}

declare module "circos/webpack.config" {
  declare module.exports: any
}

declare module "circos/webpack.config.lib" {
  declare module.exports: any
}

// Filename aliases
declare module "circos/demo/axes/index.js" {
  declare module.exports: $Exports<"circos/demo/axes/index">
}
declare module "circos/demo/chords.js" {
  declare module.exports: $Exports<"circos/demo/chords">
}
declare module "circos/demo/heatmap.js" {
  declare module.exports: $Exports<"circos/demo/heatmap">
}
declare module "circos/demo/highlight.js" {
  declare module.exports: $Exports<"circos/demo/highlight">
}
declare module "circos/demo/histogram.js" {
  declare module.exports: $Exports<"circos/demo/histogram">
}
declare module "circos/demo/line.js" {
  declare module.exports: $Exports<"circos/demo/line">
}
declare module "circos/demo/scatter.js" {
  declare module.exports: $Exports<"circos/demo/scatter">
}
declare module "circos/demo/stack.js" {
  declare module.exports: $Exports<"circos/demo/stack">
}
declare module "circos/demo/text.js" {
  declare module.exports: $Exports<"circos/demo/text">
}
declare module "circos/dist/circos.es6.js" {
  declare module.exports: $Exports<"circos/dist/circos.es6">
}
declare module "circos/dist/circos.js" {
  declare module.exports: $Exports<"circos/dist/circos">
}
declare module "circos/dist/circos.min.js" {
  declare module.exports: $Exports<"circos/dist/circos.min">
}
declare module "circos/index" {
  declare module.exports: $Exports<"circos">
}
declare module "circos/index.js" {
  declare module.exports: $Exports<"circos">
}
declare module "circos/layout-conf.js" {
  declare module.exports: $Exports<"circos/layout-conf">
}
declare module "circos/src/axes.js" {
  declare module.exports: $Exports<"circos/src/axes">
}
declare module "circos/src/axes.test.js" {
  declare module.exports: $Exports<"circos/src/axes.test">
}
declare module "circos/src/behaviors/tooltip.js" {
  declare module.exports: $Exports<"circos/src/behaviors/tooltip">
}
declare module "circos/src/circos.js" {
  declare module.exports: $Exports<"circos/src/circos">
}
declare module "circos/src/clipboard.js" {
  declare module.exports: $Exports<"circos/src/clipboard">
}
declare module "circos/src/colors.js" {
  declare module.exports: $Exports<"circos/src/colors">
}
declare module "circos/src/colors.test.js" {
  declare module.exports: $Exports<"circos/src/colors.test">
}
declare module "circos/src/config-utils.js" {
  declare module.exports: $Exports<"circos/src/config-utils">
}
declare module "circos/src/configs.js" {
  declare module.exports: $Exports<"circos/src/configs">
}
declare module "circos/src/data-parser.js" {
  declare module.exports: $Exports<"circos/src/data-parser">
}
declare module "circos/src/data-parser.test.js" {
  declare module.exports: $Exports<"circos/src/data-parser.test">
}
declare module "circos/src/layout/conf.js" {
  declare module.exports: $Exports<"circos/src/layout/conf">
}
declare module "circos/src/layout/index.js" {
  declare module.exports: $Exports<"circos/src/layout/index">
}
declare module "circos/src/layout/render.js" {
  declare module.exports: $Exports<"circos/src/layout/render">
}
declare module "circos/src/logger.js" {
  declare module.exports: $Exports<"circos/src/logger">
}
declare module "circos/src/render.js" {
  declare module.exports: $Exports<"circos/src/render">
}
declare module "circos/src/scales.js" {
  declare module.exports: $Exports<"circos/src/scales">
}
declare module "circos/src/tracks/Chords.js" {
  declare module.exports: $Exports<"circos/src/tracks/Chords">
}
declare module "circos/src/tracks/Heatmap.js" {
  declare module.exports: $Exports<"circos/src/tracks/Heatmap">
}
declare module "circos/src/tracks/Heatmap.test.js" {
  declare module.exports: $Exports<"circos/src/tracks/Heatmap.test">
}
declare module "circos/src/tracks/Highlight.js" {
  declare module.exports: $Exports<"circos/src/tracks/Highlight">
}
declare module "circos/src/tracks/Histogram.js" {
  declare module.exports: $Exports<"circos/src/tracks/Histogram">
}
declare module "circos/src/tracks/Line.js" {
  declare module.exports: $Exports<"circos/src/tracks/Line">
}
declare module "circos/src/tracks/Line.test.js" {
  declare module.exports: $Exports<"circos/src/tracks/Line.test">
}
declare module "circos/src/tracks/Scatter.js" {
  declare module.exports: $Exports<"circos/src/tracks/Scatter">
}
declare module "circos/src/tracks/Stack.js" {
  declare module.exports: $Exports<"circos/src/tracks/Stack">
}
declare module "circos/src/tracks/Text.js" {
  declare module.exports: $Exports<"circos/src/tracks/Text">
}
declare module "circos/src/tracks/Track.js" {
  declare module.exports: $Exports<"circos/src/tracks/Track">
}
declare module "circos/src/utils.js" {
  declare module.exports: $Exports<"circos/src/utils">
}
declare module "circos/src/utils.test.js" {
  declare module.exports: $Exports<"circos/src/utils.test">
}
declare module "circos/webpack.config.js" {
  declare module.exports: $Exports<"circos/webpack.config">
}
declare module "circos/webpack.config.lib.js" {
  declare module.exports: $Exports<"circos/webpack.config.lib">
}
