// flow-typed signature: 96c3b0d194ba5402a10422a14702fb74
// flow-typed version: <<STUB>>/react-loading-skeleton_v0.5.0/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-loading-skeleton'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "react-loading-skeleton" {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "react-loading-skeleton/dist/bundle" {
  declare module.exports: any
}

// Filename aliases
declare module "react-loading-skeleton/dist/bundle.js" {
  declare module.exports: $Exports<"react-loading-skeleton/dist/bundle">
}
