// flow-typed signature: f85cb9d93d8fd123aef99cb06d768ae6
// flow-typed version: <<STUB>>/react-svg-pan-zoom_v2.16.1/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-svg-pan-zoom'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "react-svg-pan-zoom" {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "react-svg-pan-zoom/build-commonjs/constants" {
  declare module.exports: any
}

declare module "react-svg-pan-zoom/build-commonjs/events/event-factory" {
  declare module.exports: any
}

declare module "react-svg-pan-zoom/build-commonjs/events/viewer-event" {
  declare module.exports: any
}

declare module "react-svg-pan-zoom/build-commonjs/events/viewer-mouse-event" {
  declare module.exports: any
}

declare module "react-svg-pan-zoom/build-commonjs/events/viewer-touch-event" {
  declare module.exports: any
}

declare module "react-svg-pan-zoom/build-commonjs/features/common" {
  declare module.exports: any
}

declare module "react-svg-pan-zoom/build-commonjs/features/interactions-touch" {
  declare module.exports: any
}

declare module "react-svg-pan-zoom/build-commonjs/features/interactions" {
  declare module.exports: any
}

declare module "react-svg-pan-zoom/build-commonjs/features/miniature" {
  declare module.exports: any
}

declare module "react-svg-pan-zoom/build-commonjs/features/pan" {
  declare module.exports: any
}

declare module "react-svg-pan-zoom/build-commonjs/features/zoom" {
  declare module.exports: any
}

declare module "react-svg-pan-zoom/build-commonjs/index" {
  declare module.exports: any
}

declare module "react-svg-pan-zoom/build-commonjs/ui-miniature/icon-arrow" {
  declare module.exports: any
}

declare module "react-svg-pan-zoom/build-commonjs/ui-miniature/miniature-mask" {
  declare module.exports: any
}

declare module "react-svg-pan-zoom/build-commonjs/ui-miniature/miniature-toggle-button" {
  declare module.exports: any
}

declare module "react-svg-pan-zoom/build-commonjs/ui-miniature/miniature" {
  declare module.exports: any
}

declare module "react-svg-pan-zoom/build-commonjs/ui-toolbar/icon-cursor" {
  declare module.exports: any
}

declare module "react-svg-pan-zoom/build-commonjs/ui-toolbar/icon-fit" {
  declare module.exports: any
}

declare module "react-svg-pan-zoom/build-commonjs/ui-toolbar/icon-pan" {
  declare module.exports: any
}

declare module "react-svg-pan-zoom/build-commonjs/ui-toolbar/icon-zoom-in" {
  declare module.exports: any
}

declare module "react-svg-pan-zoom/build-commonjs/ui-toolbar/icon-zoom-out" {
  declare module.exports: any
}

declare module "react-svg-pan-zoom/build-commonjs/ui-toolbar/toolbar-button" {
  declare module.exports: any
}

declare module "react-svg-pan-zoom/build-commonjs/ui-toolbar/toolbar" {
  declare module.exports: any
}

declare module "react-svg-pan-zoom/build-commonjs/ui/border-gradient" {
  declare module.exports: any
}

declare module "react-svg-pan-zoom/build-commonjs/ui/cursor-polyfill" {
  declare module.exports: any
}

declare module "react-svg-pan-zoom/build-commonjs/ui/detect-touch" {
  declare module.exports: any
}

declare module "react-svg-pan-zoom/build-commonjs/ui/selection" {
  declare module.exports: any
}

declare module "react-svg-pan-zoom/build-commonjs/utils/calculateBox" {
  declare module.exports: any
}

declare module "react-svg-pan-zoom/build-commonjs/utils/getDisplayName" {
  declare module.exports: any
}

declare module "react-svg-pan-zoom/build-commonjs/utils/mapRange" {
  declare module.exports: any
}

declare module "react-svg-pan-zoom/build-commonjs/utils/RandomUID" {
  declare module.exports: any
}

declare module "react-svg-pan-zoom/build-commonjs/viewer" {
  declare module.exports: any
}

declare module "react-svg-pan-zoom/build-es/constants" {
  declare module.exports: any
}

declare module "react-svg-pan-zoom/build-es/events/event-factory" {
  declare module.exports: any
}

declare module "react-svg-pan-zoom/build-es/events/viewer-event" {
  declare module.exports: any
}

declare module "react-svg-pan-zoom/build-es/events/viewer-mouse-event" {
  declare module.exports: any
}

declare module "react-svg-pan-zoom/build-es/events/viewer-touch-event" {
  declare module.exports: any
}

declare module "react-svg-pan-zoom/build-es/features/common" {
  declare module.exports: any
}

declare module "react-svg-pan-zoom/build-es/features/interactions-touch" {
  declare module.exports: any
}

declare module "react-svg-pan-zoom/build-es/features/interactions" {
  declare module.exports: any
}

declare module "react-svg-pan-zoom/build-es/features/miniature" {
  declare module.exports: any
}

declare module "react-svg-pan-zoom/build-es/features/pan" {
  declare module.exports: any
}

declare module "react-svg-pan-zoom/build-es/features/zoom" {
  declare module.exports: any
}

declare module "react-svg-pan-zoom/build-es/index" {
  declare module.exports: any
}

declare module "react-svg-pan-zoom/build-es/ui-miniature/icon-arrow" {
  declare module.exports: any
}

declare module "react-svg-pan-zoom/build-es/ui-miniature/miniature-mask" {
  declare module.exports: any
}

declare module "react-svg-pan-zoom/build-es/ui-miniature/miniature-toggle-button" {
  declare module.exports: any
}

declare module "react-svg-pan-zoom/build-es/ui-miniature/miniature" {
  declare module.exports: any
}

declare module "react-svg-pan-zoom/build-es/ui-toolbar/icon-cursor" {
  declare module.exports: any
}

declare module "react-svg-pan-zoom/build-es/ui-toolbar/icon-fit" {
  declare module.exports: any
}

declare module "react-svg-pan-zoom/build-es/ui-toolbar/icon-pan" {
  declare module.exports: any
}

declare module "react-svg-pan-zoom/build-es/ui-toolbar/icon-zoom-in" {
  declare module.exports: any
}

declare module "react-svg-pan-zoom/build-es/ui-toolbar/icon-zoom-out" {
  declare module.exports: any
}

declare module "react-svg-pan-zoom/build-es/ui-toolbar/toolbar-button" {
  declare module.exports: any
}

declare module "react-svg-pan-zoom/build-es/ui-toolbar/toolbar" {
  declare module.exports: any
}

declare module "react-svg-pan-zoom/build-es/ui/border-gradient" {
  declare module.exports: any
}

declare module "react-svg-pan-zoom/build-es/ui/cursor-polyfill" {
  declare module.exports: any
}

declare module "react-svg-pan-zoom/build-es/ui/detect-touch" {
  declare module.exports: any
}

declare module "react-svg-pan-zoom/build-es/ui/selection" {
  declare module.exports: any
}

declare module "react-svg-pan-zoom/build-es/utils/calculateBox" {
  declare module.exports: any
}

declare module "react-svg-pan-zoom/build-es/utils/getDisplayName" {
  declare module.exports: any
}

declare module "react-svg-pan-zoom/build-es/utils/mapRange" {
  declare module.exports: any
}

declare module "react-svg-pan-zoom/build-es/utils/RandomUID" {
  declare module.exports: any
}

declare module "react-svg-pan-zoom/build-es/viewer" {
  declare module.exports: any
}

declare module "react-svg-pan-zoom/build-storybook/static/manager.99051738a0d6b840fc95.bundle" {
  declare module.exports: any
}

declare module "react-svg-pan-zoom/build-storybook/static/preview.b8650dfa82eda8c3518a.bundle" {
  declare module.exports: any
}

declare module "react-svg-pan-zoom/build-umd/react-svg-pan-zoom" {
  declare module.exports: any
}

declare module "react-svg-pan-zoom/build-umd/react-svg-pan-zoom.min" {
  declare module.exports: any
}

declare module "react-svg-pan-zoom/src/constants" {
  declare module.exports: any
}

declare module "react-svg-pan-zoom/src/events/event-factory" {
  declare module.exports: any
}

declare module "react-svg-pan-zoom/src/events/viewer-event" {
  declare module.exports: any
}

declare module "react-svg-pan-zoom/src/events/viewer-mouse-event" {
  declare module.exports: any
}

declare module "react-svg-pan-zoom/src/events/viewer-touch-event" {
  declare module.exports: any
}

declare module "react-svg-pan-zoom/src/features/common" {
  declare module.exports: any
}

declare module "react-svg-pan-zoom/src/features/interactions-touch" {
  declare module.exports: any
}

declare module "react-svg-pan-zoom/src/features/interactions" {
  declare module.exports: any
}

declare module "react-svg-pan-zoom/src/features/miniature" {
  declare module.exports: any
}

declare module "react-svg-pan-zoom/src/features/pan" {
  declare module.exports: any
}

declare module "react-svg-pan-zoom/src/features/zoom" {
  declare module.exports: any
}

declare module "react-svg-pan-zoom/src/index" {
  declare module.exports: any
}

declare module "react-svg-pan-zoom/src/ui-miniature/icon-arrow" {
  declare module.exports: any
}

declare module "react-svg-pan-zoom/src/ui-miniature/miniature-mask" {
  declare module.exports: any
}

declare module "react-svg-pan-zoom/src/ui-miniature/miniature-toggle-button" {
  declare module.exports: any
}

declare module "react-svg-pan-zoom/src/ui-miniature/miniature" {
  declare module.exports: any
}

declare module "react-svg-pan-zoom/src/ui-toolbar/icon-cursor" {
  declare module.exports: any
}

declare module "react-svg-pan-zoom/src/ui-toolbar/icon-fit" {
  declare module.exports: any
}

declare module "react-svg-pan-zoom/src/ui-toolbar/icon-pan" {
  declare module.exports: any
}

declare module "react-svg-pan-zoom/src/ui-toolbar/icon-zoom-in" {
  declare module.exports: any
}

declare module "react-svg-pan-zoom/src/ui-toolbar/icon-zoom-out" {
  declare module.exports: any
}

declare module "react-svg-pan-zoom/src/ui-toolbar/toolbar-button" {
  declare module.exports: any
}

declare module "react-svg-pan-zoom/src/ui-toolbar/toolbar" {
  declare module.exports: any
}

declare module "react-svg-pan-zoom/src/ui/border-gradient" {
  declare module.exports: any
}

declare module "react-svg-pan-zoom/src/ui/cursor-polyfill" {
  declare module.exports: any
}

declare module "react-svg-pan-zoom/src/ui/detect-touch" {
  declare module.exports: any
}

declare module "react-svg-pan-zoom/src/ui/selection" {
  declare module.exports: any
}

declare module "react-svg-pan-zoom/src/utils/calculateBox" {
  declare module.exports: any
}

declare module "react-svg-pan-zoom/src/utils/getDisplayName" {
  declare module.exports: any
}

declare module "react-svg-pan-zoom/src/utils/mapRange" {
  declare module.exports: any
}

declare module "react-svg-pan-zoom/src/utils/RandomUID" {
  declare module.exports: any
}

declare module "react-svg-pan-zoom/src/viewer" {
  declare module.exports: any
}

// Filename aliases
declare module "react-svg-pan-zoom/build-commonjs/constants.js" {
  declare module.exports: $Exports<
    "react-svg-pan-zoom/build-commonjs/constants",
  >
}
declare module "react-svg-pan-zoom/build-commonjs/events/event-factory.js" {
  declare module.exports: $Exports<
    "react-svg-pan-zoom/build-commonjs/events/event-factory",
  >
}
declare module "react-svg-pan-zoom/build-commonjs/events/viewer-event.js" {
  declare module.exports: $Exports<
    "react-svg-pan-zoom/build-commonjs/events/viewer-event",
  >
}
declare module "react-svg-pan-zoom/build-commonjs/events/viewer-mouse-event.js" {
  declare module.exports: $Exports<
    "react-svg-pan-zoom/build-commonjs/events/viewer-mouse-event",
  >
}
declare module "react-svg-pan-zoom/build-commonjs/events/viewer-touch-event.js" {
  declare module.exports: $Exports<
    "react-svg-pan-zoom/build-commonjs/events/viewer-touch-event",
  >
}
declare module "react-svg-pan-zoom/build-commonjs/features/common.js" {
  declare module.exports: $Exports<
    "react-svg-pan-zoom/build-commonjs/features/common",
  >
}
declare module "react-svg-pan-zoom/build-commonjs/features/interactions-touch.js" {
  declare module.exports: $Exports<
    "react-svg-pan-zoom/build-commonjs/features/interactions-touch",
  >
}
declare module "react-svg-pan-zoom/build-commonjs/features/interactions.js" {
  declare module.exports: $Exports<
    "react-svg-pan-zoom/build-commonjs/features/interactions",
  >
}
declare module "react-svg-pan-zoom/build-commonjs/features/miniature.js" {
  declare module.exports: $Exports<
    "react-svg-pan-zoom/build-commonjs/features/miniature",
  >
}
declare module "react-svg-pan-zoom/build-commonjs/features/pan.js" {
  declare module.exports: $Exports<
    "react-svg-pan-zoom/build-commonjs/features/pan",
  >
}
declare module "react-svg-pan-zoom/build-commonjs/features/zoom.js" {
  declare module.exports: $Exports<
    "react-svg-pan-zoom/build-commonjs/features/zoom",
  >
}
declare module "react-svg-pan-zoom/build-commonjs/index.js" {
  declare module.exports: $Exports<"react-svg-pan-zoom/build-commonjs/index">
}
declare module "react-svg-pan-zoom/build-commonjs/ui-miniature/icon-arrow.js" {
  declare module.exports: $Exports<
    "react-svg-pan-zoom/build-commonjs/ui-miniature/icon-arrow",
  >
}
declare module "react-svg-pan-zoom/build-commonjs/ui-miniature/miniature-mask.js" {
  declare module.exports: $Exports<
    "react-svg-pan-zoom/build-commonjs/ui-miniature/miniature-mask",
  >
}
declare module "react-svg-pan-zoom/build-commonjs/ui-miniature/miniature-toggle-button.js" {
  declare module.exports: $Exports<
    "react-svg-pan-zoom/build-commonjs/ui-miniature/miniature-toggle-button",
  >
}
declare module "react-svg-pan-zoom/build-commonjs/ui-miniature/miniature.js" {
  declare module.exports: $Exports<
    "react-svg-pan-zoom/build-commonjs/ui-miniature/miniature",
  >
}
declare module "react-svg-pan-zoom/build-commonjs/ui-toolbar/icon-cursor.js" {
  declare module.exports: $Exports<
    "react-svg-pan-zoom/build-commonjs/ui-toolbar/icon-cursor",
  >
}
declare module "react-svg-pan-zoom/build-commonjs/ui-toolbar/icon-fit.js" {
  declare module.exports: $Exports<
    "react-svg-pan-zoom/build-commonjs/ui-toolbar/icon-fit",
  >
}
declare module "react-svg-pan-zoom/build-commonjs/ui-toolbar/icon-pan.js" {
  declare module.exports: $Exports<
    "react-svg-pan-zoom/build-commonjs/ui-toolbar/icon-pan",
  >
}
declare module "react-svg-pan-zoom/build-commonjs/ui-toolbar/icon-zoom-in.js" {
  declare module.exports: $Exports<
    "react-svg-pan-zoom/build-commonjs/ui-toolbar/icon-zoom-in",
  >
}
declare module "react-svg-pan-zoom/build-commonjs/ui-toolbar/icon-zoom-out.js" {
  declare module.exports: $Exports<
    "react-svg-pan-zoom/build-commonjs/ui-toolbar/icon-zoom-out",
  >
}
declare module "react-svg-pan-zoom/build-commonjs/ui-toolbar/toolbar-button.js" {
  declare module.exports: $Exports<
    "react-svg-pan-zoom/build-commonjs/ui-toolbar/toolbar-button",
  >
}
declare module "react-svg-pan-zoom/build-commonjs/ui-toolbar/toolbar.js" {
  declare module.exports: $Exports<
    "react-svg-pan-zoom/build-commonjs/ui-toolbar/toolbar",
  >
}
declare module "react-svg-pan-zoom/build-commonjs/ui/border-gradient.js" {
  declare module.exports: $Exports<
    "react-svg-pan-zoom/build-commonjs/ui/border-gradient",
  >
}
declare module "react-svg-pan-zoom/build-commonjs/ui/cursor-polyfill.js" {
  declare module.exports: $Exports<
    "react-svg-pan-zoom/build-commonjs/ui/cursor-polyfill",
  >
}
declare module "react-svg-pan-zoom/build-commonjs/ui/detect-touch.js" {
  declare module.exports: $Exports<
    "react-svg-pan-zoom/build-commonjs/ui/detect-touch",
  >
}
declare module "react-svg-pan-zoom/build-commonjs/ui/selection.js" {
  declare module.exports: $Exports<
    "react-svg-pan-zoom/build-commonjs/ui/selection",
  >
}
declare module "react-svg-pan-zoom/build-commonjs/utils/calculateBox.js" {
  declare module.exports: $Exports<
    "react-svg-pan-zoom/build-commonjs/utils/calculateBox",
  >
}
declare module "react-svg-pan-zoom/build-commonjs/utils/getDisplayName.js" {
  declare module.exports: $Exports<
    "react-svg-pan-zoom/build-commonjs/utils/getDisplayName",
  >
}
declare module "react-svg-pan-zoom/build-commonjs/utils/mapRange.js" {
  declare module.exports: $Exports<
    "react-svg-pan-zoom/build-commonjs/utils/mapRange",
  >
}
declare module "react-svg-pan-zoom/build-commonjs/utils/RandomUID.js" {
  declare module.exports: $Exports<
    "react-svg-pan-zoom/build-commonjs/utils/RandomUID",
  >
}
declare module "react-svg-pan-zoom/build-commonjs/viewer.js" {
  declare module.exports: $Exports<"react-svg-pan-zoom/build-commonjs/viewer">
}
declare module "react-svg-pan-zoom/build-es/constants.js" {
  declare module.exports: $Exports<"react-svg-pan-zoom/build-es/constants">
}
declare module "react-svg-pan-zoom/build-es/events/event-factory.js" {
  declare module.exports: $Exports<
    "react-svg-pan-zoom/build-es/events/event-factory",
  >
}
declare module "react-svg-pan-zoom/build-es/events/viewer-event.js" {
  declare module.exports: $Exports<
    "react-svg-pan-zoom/build-es/events/viewer-event",
  >
}
declare module "react-svg-pan-zoom/build-es/events/viewer-mouse-event.js" {
  declare module.exports: $Exports<
    "react-svg-pan-zoom/build-es/events/viewer-mouse-event",
  >
}
declare module "react-svg-pan-zoom/build-es/events/viewer-touch-event.js" {
  declare module.exports: $Exports<
    "react-svg-pan-zoom/build-es/events/viewer-touch-event",
  >
}
declare module "react-svg-pan-zoom/build-es/features/common.js" {
  declare module.exports: $Exports<
    "react-svg-pan-zoom/build-es/features/common",
  >
}
declare module "react-svg-pan-zoom/build-es/features/interactions-touch.js" {
  declare module.exports: $Exports<
    "react-svg-pan-zoom/build-es/features/interactions-touch",
  >
}
declare module "react-svg-pan-zoom/build-es/features/interactions.js" {
  declare module.exports: $Exports<
    "react-svg-pan-zoom/build-es/features/interactions",
  >
}
declare module "react-svg-pan-zoom/build-es/features/miniature.js" {
  declare module.exports: $Exports<
    "react-svg-pan-zoom/build-es/features/miniature",
  >
}
declare module "react-svg-pan-zoom/build-es/features/pan.js" {
  declare module.exports: $Exports<"react-svg-pan-zoom/build-es/features/pan">
}
declare module "react-svg-pan-zoom/build-es/features/zoom.js" {
  declare module.exports: $Exports<"react-svg-pan-zoom/build-es/features/zoom">
}
declare module "react-svg-pan-zoom/build-es/index.js" {
  declare module.exports: $Exports<"react-svg-pan-zoom/build-es/index">
}
declare module "react-svg-pan-zoom/build-es/ui-miniature/icon-arrow.js" {
  declare module.exports: $Exports<
    "react-svg-pan-zoom/build-es/ui-miniature/icon-arrow",
  >
}
declare module "react-svg-pan-zoom/build-es/ui-miniature/miniature-mask.js" {
  declare module.exports: $Exports<
    "react-svg-pan-zoom/build-es/ui-miniature/miniature-mask",
  >
}
declare module "react-svg-pan-zoom/build-es/ui-miniature/miniature-toggle-button.js" {
  declare module.exports: $Exports<
    "react-svg-pan-zoom/build-es/ui-miniature/miniature-toggle-button",
  >
}
declare module "react-svg-pan-zoom/build-es/ui-miniature/miniature.js" {
  declare module.exports: $Exports<
    "react-svg-pan-zoom/build-es/ui-miniature/miniature",
  >
}
declare module "react-svg-pan-zoom/build-es/ui-toolbar/icon-cursor.js" {
  declare module.exports: $Exports<
    "react-svg-pan-zoom/build-es/ui-toolbar/icon-cursor",
  >
}
declare module "react-svg-pan-zoom/build-es/ui-toolbar/icon-fit.js" {
  declare module.exports: $Exports<
    "react-svg-pan-zoom/build-es/ui-toolbar/icon-fit",
  >
}
declare module "react-svg-pan-zoom/build-es/ui-toolbar/icon-pan.js" {
  declare module.exports: $Exports<
    "react-svg-pan-zoom/build-es/ui-toolbar/icon-pan",
  >
}
declare module "react-svg-pan-zoom/build-es/ui-toolbar/icon-zoom-in.js" {
  declare module.exports: $Exports<
    "react-svg-pan-zoom/build-es/ui-toolbar/icon-zoom-in",
  >
}
declare module "react-svg-pan-zoom/build-es/ui-toolbar/icon-zoom-out.js" {
  declare module.exports: $Exports<
    "react-svg-pan-zoom/build-es/ui-toolbar/icon-zoom-out",
  >
}
declare module "react-svg-pan-zoom/build-es/ui-toolbar/toolbar-button.js" {
  declare module.exports: $Exports<
    "react-svg-pan-zoom/build-es/ui-toolbar/toolbar-button",
  >
}
declare module "react-svg-pan-zoom/build-es/ui-toolbar/toolbar.js" {
  declare module.exports: $Exports<
    "react-svg-pan-zoom/build-es/ui-toolbar/toolbar",
  >
}
declare module "react-svg-pan-zoom/build-es/ui/border-gradient.js" {
  declare module.exports: $Exports<
    "react-svg-pan-zoom/build-es/ui/border-gradient",
  >
}
declare module "react-svg-pan-zoom/build-es/ui/cursor-polyfill.js" {
  declare module.exports: $Exports<
    "react-svg-pan-zoom/build-es/ui/cursor-polyfill",
  >
}
declare module "react-svg-pan-zoom/build-es/ui/detect-touch.js" {
  declare module.exports: $Exports<
    "react-svg-pan-zoom/build-es/ui/detect-touch",
  >
}
declare module "react-svg-pan-zoom/build-es/ui/selection.js" {
  declare module.exports: $Exports<"react-svg-pan-zoom/build-es/ui/selection">
}
declare module "react-svg-pan-zoom/build-es/utils/calculateBox.js" {
  declare module.exports: $Exports<
    "react-svg-pan-zoom/build-es/utils/calculateBox",
  >
}
declare module "react-svg-pan-zoom/build-es/utils/getDisplayName.js" {
  declare module.exports: $Exports<
    "react-svg-pan-zoom/build-es/utils/getDisplayName",
  >
}
declare module "react-svg-pan-zoom/build-es/utils/mapRange.js" {
  declare module.exports: $Exports<"react-svg-pan-zoom/build-es/utils/mapRange">
}
declare module "react-svg-pan-zoom/build-es/utils/RandomUID.js" {
  declare module.exports: $Exports<
    "react-svg-pan-zoom/build-es/utils/RandomUID",
  >
}
declare module "react-svg-pan-zoom/build-es/viewer.js" {
  declare module.exports: $Exports<"react-svg-pan-zoom/build-es/viewer">
}
declare module "react-svg-pan-zoom/build-storybook/static/manager.99051738a0d6b840fc95.bundle.js" {
  declare module.exports: $Exports<
    "react-svg-pan-zoom/build-storybook/static/manager.99051738a0d6b840fc95.bundle",
  >
}
declare module "react-svg-pan-zoom/build-storybook/static/preview.b8650dfa82eda8c3518a.bundle.js" {
  declare module.exports: $Exports<
    "react-svg-pan-zoom/build-storybook/static/preview.b8650dfa82eda8c3518a.bundle",
  >
}
declare module "react-svg-pan-zoom/build-umd/react-svg-pan-zoom.js" {
  declare module.exports: $Exports<
    "react-svg-pan-zoom/build-umd/react-svg-pan-zoom",
  >
}
declare module "react-svg-pan-zoom/build-umd/react-svg-pan-zoom.min.js" {
  declare module.exports: $Exports<
    "react-svg-pan-zoom/build-umd/react-svg-pan-zoom.min",
  >
}
declare module "react-svg-pan-zoom/src/constants.js" {
  declare module.exports: $Exports<"react-svg-pan-zoom/src/constants">
}
declare module "react-svg-pan-zoom/src/events/event-factory.js" {
  declare module.exports: $Exports<
    "react-svg-pan-zoom/src/events/event-factory",
  >
}
declare module "react-svg-pan-zoom/src/events/viewer-event.js" {
  declare module.exports: $Exports<"react-svg-pan-zoom/src/events/viewer-event">
}
declare module "react-svg-pan-zoom/src/events/viewer-mouse-event.js" {
  declare module.exports: $Exports<
    "react-svg-pan-zoom/src/events/viewer-mouse-event",
  >
}
declare module "react-svg-pan-zoom/src/events/viewer-touch-event.js" {
  declare module.exports: $Exports<
    "react-svg-pan-zoom/src/events/viewer-touch-event",
  >
}
declare module "react-svg-pan-zoom/src/features/common.js" {
  declare module.exports: $Exports<"react-svg-pan-zoom/src/features/common">
}
declare module "react-svg-pan-zoom/src/features/interactions-touch.js" {
  declare module.exports: $Exports<
    "react-svg-pan-zoom/src/features/interactions-touch",
  >
}
declare module "react-svg-pan-zoom/src/features/interactions.js" {
  declare module.exports: $Exports<
    "react-svg-pan-zoom/src/features/interactions",
  >
}
declare module "react-svg-pan-zoom/src/features/miniature.js" {
  declare module.exports: $Exports<"react-svg-pan-zoom/src/features/miniature">
}
declare module "react-svg-pan-zoom/src/features/pan.js" {
  declare module.exports: $Exports<"react-svg-pan-zoom/src/features/pan">
}
declare module "react-svg-pan-zoom/src/features/zoom.js" {
  declare module.exports: $Exports<"react-svg-pan-zoom/src/features/zoom">
}
declare module "react-svg-pan-zoom/src/index.js" {
  declare module.exports: $Exports<"react-svg-pan-zoom/src/index">
}
declare module "react-svg-pan-zoom/src/ui-miniature/icon-arrow.jsx" {
  declare module.exports: $Exports<
    "react-svg-pan-zoom/src/ui-miniature/icon-arrow",
  >
}
declare module "react-svg-pan-zoom/src/ui-miniature/miniature-mask.jsx" {
  declare module.exports: $Exports<
    "react-svg-pan-zoom/src/ui-miniature/miniature-mask",
  >
}
declare module "react-svg-pan-zoom/src/ui-miniature/miniature-toggle-button.jsx" {
  declare module.exports: $Exports<
    "react-svg-pan-zoom/src/ui-miniature/miniature-toggle-button",
  >
}
declare module "react-svg-pan-zoom/src/ui-miniature/miniature.jsx" {
  declare module.exports: $Exports<
    "react-svg-pan-zoom/src/ui-miniature/miniature",
  >
}
declare module "react-svg-pan-zoom/src/ui-toolbar/icon-cursor.jsx" {
  declare module.exports: $Exports<
    "react-svg-pan-zoom/src/ui-toolbar/icon-cursor",
  >
}
declare module "react-svg-pan-zoom/src/ui-toolbar/icon-fit.jsx" {
  declare module.exports: $Exports<"react-svg-pan-zoom/src/ui-toolbar/icon-fit">
}
declare module "react-svg-pan-zoom/src/ui-toolbar/icon-pan.jsx" {
  declare module.exports: $Exports<"react-svg-pan-zoom/src/ui-toolbar/icon-pan">
}
declare module "react-svg-pan-zoom/src/ui-toolbar/icon-zoom-in.jsx" {
  declare module.exports: $Exports<
    "react-svg-pan-zoom/src/ui-toolbar/icon-zoom-in",
  >
}
declare module "react-svg-pan-zoom/src/ui-toolbar/icon-zoom-out.jsx" {
  declare module.exports: $Exports<
    "react-svg-pan-zoom/src/ui-toolbar/icon-zoom-out",
  >
}
declare module "react-svg-pan-zoom/src/ui-toolbar/toolbar-button.jsx" {
  declare module.exports: $Exports<
    "react-svg-pan-zoom/src/ui-toolbar/toolbar-button",
  >
}
declare module "react-svg-pan-zoom/src/ui-toolbar/toolbar.jsx" {
  declare module.exports: $Exports<"react-svg-pan-zoom/src/ui-toolbar/toolbar">
}
declare module "react-svg-pan-zoom/src/ui/border-gradient.js" {
  declare module.exports: $Exports<"react-svg-pan-zoom/src/ui/border-gradient">
}
declare module "react-svg-pan-zoom/src/ui/cursor-polyfill.js" {
  declare module.exports: $Exports<"react-svg-pan-zoom/src/ui/cursor-polyfill">
}
declare module "react-svg-pan-zoom/src/ui/detect-touch.js" {
  declare module.exports: $Exports<"react-svg-pan-zoom/src/ui/detect-touch">
}
declare module "react-svg-pan-zoom/src/ui/selection.jsx" {
  declare module.exports: $Exports<"react-svg-pan-zoom/src/ui/selection">
}
declare module "react-svg-pan-zoom/src/utils/calculateBox.js" {
  declare module.exports: $Exports<"react-svg-pan-zoom/src/utils/calculateBox">
}
declare module "react-svg-pan-zoom/src/utils/getDisplayName.js" {
  declare module.exports: $Exports<
    "react-svg-pan-zoom/src/utils/getDisplayName",
  >
}
declare module "react-svg-pan-zoom/src/utils/mapRange.js" {
  declare module.exports: $Exports<"react-svg-pan-zoom/src/utils/mapRange">
}
declare module "react-svg-pan-zoom/src/utils/RandomUID.js" {
  declare module.exports: $Exports<"react-svg-pan-zoom/src/utils/RandomUID">
}
declare module "react-svg-pan-zoom/src/viewer.js" {
  declare module.exports: $Exports<"react-svg-pan-zoom/src/viewer">
}
