export const AppStyles = (theme) => ({
  container: {
    marginRight: "auto",
    marginLeft: "auto",
    height: "100%",
    zIndex: 1,
    overflow: "hidden",
    position: "relative",
    display: "flex",
    width: "100%",
  },
  mainContent: {
    flexGrow: 1,
    backgroundColor: "#ced4da",
    padding: "16px",
    marginLeft: "0px",
  },
  body: {
    margin: "auto",
    height: "100%",
    width: "100%",
    fontFamily: "Roboto, sans-serif",
    fontSize: "16px",
    // lineHeight: 1.42857,
    color: "#333",
    backgroundColor: "#fff",
    boxSizing: "border-box",
    WebkitFontSmoothing: "auto",
    MozOsxFontSmoothing: "auto",
  },
})
